// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: api/tally/v1/transaction.proto

package transactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionType defines income or expense.
// 交易类型：收入或支出
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0 // 未指定 / Unspecified
	TransactionType_TRANSACTION_TYPE_INCOME      TransactionType = 1 // 收入 / Income
	TransactionType_TRANSACTION_TYPE_EXPENSE     TransactionType = 2 // 支出 / Expense
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_INCOME",
		2: "TRANSACTION_TYPE_EXPENSE",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_INCOME":      1,
		"TRANSACTION_TYPE_EXPENSE":     2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tally_v1_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_api_tally_v1_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{0}
}

// Transaction represents a single financial record.
// 交易记录实体（单条账目）
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier, system generated (e.g., UUID).
	// 唯一标识符，系统生成（如 UUID）。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Transaction type: income or expense.
	// 交易类型：收入或支出。
	Type TransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=tally.v1.TransactionType" json:"type,omitempty"`
	// Amount in minor units (cents for CNY), always positive.
	// Use int64 to avoid floating point precision issues.
	// 金额，以最小货币单位存储（人民币分）。始终为正数，使用int64避免浮点误差。
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Category name, e.g., "餐饮" (Food), "交通" (Transport), "工资" (Salary).
	// User can input any string, no need to pre-define categories.
	// 分类名称，例如："餐饮"、"交通"、"工资"。用户可自由输入，无需预定义分类。
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Description or notes about this transaction.
	// 交易描述或备注。
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// The actual transaction time (user specified), not record creation time.
	// 实际交易时间（用户指定），非记录创建时间。
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Record creation timestamp, system generated.
	// 记录创建时间，系统生成。
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// RecordRequest creates a new transaction.
// 记账请求（创建交易记录）
type RecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must be INCOME or EXPENSE.
	// 必须是收入或支出类型。
	Type TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=tally.v1.TransactionType" json:"type,omitempty"`
	// Amount in minor units (e.g., 12345 means ¥123.45).
	// Must be greater than 0.
	// 金额（最小单位，如12345表示123.45元）。必须大于0。
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Category label, required.
	// 分类标签，必填。
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	// Optional description.
	// 可选描述。
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Optional transaction time. If not set, uses current time.
	// 可选交易时间，如不设置则使用当前时间。
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *RecordRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *RecordRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RecordRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordRequest) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

// ListRequest queries transactions with filters.
// 查账请求（列表查询，支持筛选）
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by transaction type. If unspecified, returns all types.
	// 按类型筛选，如不指定则返回所有类型。
	FilterType TransactionType `protobuf:"varint,1,opt,name=filter_type,json=filterType,proto3,enum=tally.v1.TransactionType" json:"filter_type,omitempty"`
	// Filter by category name (exact match). Empty means all categories.
	// 按分类筛选（精确匹配），为空表示所有分类。
	FilterCategory string `protobuf:"bytes,2,opt,name=filter_category,json=filterCategory,proto3" json:"filter_category,omitempty"`
	// Filter by start time (inclusive). Empty means no lower bound.
	// 开始时间筛选（包含），为空表示不限制起始时间。
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Filter by end time (inclusive). Empty means no upper bound.
	// 结束时间筛选（包含），为空表示不限制结束时间。
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Pagination: page number, 1-based (first page is 1).
	// 分页页码，从1开始。
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// Pagination: items per page, default 20, max 100.
	// 每页数量，默认20，最大100。
	PageSize      int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetFilterType() TransactionType {
	if x != nil {
		return x.FilterType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *ListRequest) GetFilterCategory() string {
	if x != nil {
		return x.FilterCategory
	}
	return ""
}

func (x *ListRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListResponse returns transactions and pagination info.
// 查账响应（返回列表和分页信息）
type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transactions.
	// 交易记录列表。
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Total count of matching records (for pagination).
	// 符合条件的总记录数（用于分页显示）。
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Current page number.
	// 当前页码。
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Current page size.
	// 当前页大小。
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetRequest retrieves a single transaction by ID.
// 单条查询请求
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID.
	// 交易记录ID。
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteRequest removes a transaction.
// 删除请求（记错了可以删）
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_tally_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tally_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_tally_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_tally_v1_transaction_proto protoreflect.FileDescriptor

const file_api_tally_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/tally/v1/transaction.proto\x12\btally.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa4\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.tally.v1.TransactionTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12E\n" +
	"\x10transaction_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdb\x01\n" +
	"\rRecordRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.tally.v1.TransactionTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12E\n" +
	"\x10transaction_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"\x95\x02\n" +
	"\vListRequest\x12:\n" +
	"\vfilter_type\x18\x01 \x01(\x0e2\x19.tally.v1.TransactionTypeR\n" +
	"filterType\x12'\n" +
	"\x0ffilter_category\x18\x02 \x01(\tR\x0efilterCategory\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x9b\x01\n" +
	"\fListResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.tally.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*n\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_INCOME\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_EXPENSE\x10\x022\xee\x01\n" +
	"\fTallyService\x128\n" +
	"\x06Record\x12\x17.tally.v1.RecordRequest\x1a\x15.tally.v1.Transaction\x125\n" +
	"\x04List\x12\x15.tally.v1.ListRequest\x1a\x16.tally.v1.ListResponse\x122\n" +
	"\x03Get\x12\x14.tally.v1.GetRequest\x1a\x15.tally.v1.Transaction\x129\n" +
	"\x06Delete\x12\x17.tally.v1.DeleteRequest\x1a\x16.google.protobuf.EmptyB6Z4github.com/ww916/ww-tally/api/tally/v1;transactionpbb\x06proto3"

var (
	file_api_tally_v1_transaction_proto_rawDescOnce sync.Once
	file_api_tally_v1_transaction_proto_rawDescData []byte
)

func file_api_tally_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_tally_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_tally_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tally_v1_transaction_proto_rawDesc), len(file_api_tally_v1_transaction_proto_rawDesc)))
	})
	return file_api_tally_v1_transaction_proto_rawDescData
}

var file_api_tally_v1_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_tally_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_tally_v1_transaction_proto_goTypes = []any{
	(TransactionType)(0),          // 0: tally.v1.TransactionType
	(*Transaction)(nil),           // 1: tally.v1.Transaction
	(*RecordRequest)(nil),         // 2: tally.v1.RecordRequest
	(*ListRequest)(nil),           // 3: tally.v1.ListRequest
	(*ListResponse)(nil),          // 4: tally.v1.ListResponse
	(*GetRequest)(nil),            // 5: tally.v1.GetRequest
	(*DeleteRequest)(nil),         // 6: tally.v1.DeleteRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_api_tally_v1_transaction_proto_depIdxs = []int32{
	0,  // 0: tally.v1.Transaction.type:type_name -> tally.v1.TransactionType
	7,  // 1: tally.v1.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	7,  // 2: tally.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: tally.v1.RecordRequest.type:type_name -> tally.v1.TransactionType
	7,  // 4: tally.v1.RecordRequest.transaction_time:type_name -> google.protobuf.Timestamp
	0,  // 5: tally.v1.ListRequest.filter_type:type_name -> tally.v1.TransactionType
	7,  // 6: tally.v1.ListRequest.start_time:type_name -> google.protobuf.Timestamp
	7,  // 7: tally.v1.ListRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 8: tally.v1.ListResponse.transactions:type_name -> tally.v1.Transaction
	2,  // 9: tally.v1.TallyService.Record:input_type -> tally.v1.RecordRequest
	3,  // 10: tally.v1.TallyService.List:input_type -> tally.v1.ListRequest
	5,  // 11: tally.v1.TallyService.Get:input_type -> tally.v1.GetRequest
	6,  // 12: tally.v1.TallyService.Delete:input_type -> tally.v1.DeleteRequest
	1,  // 13: tally.v1.TallyService.Record:output_type -> tally.v1.Transaction
	4,  // 14: tally.v1.TallyService.List:output_type -> tally.v1.ListResponse
	1,  // 15: tally.v1.TallyService.Get:output_type -> tally.v1.Transaction
	8,  // 16: tally.v1.TallyService.Delete:output_type -> google.protobuf.Empty
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_tally_v1_transaction_proto_init() }
func file_api_tally_v1_transaction_proto_init() {
	if File_api_tally_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tally_v1_transaction_proto_rawDesc), len(file_api_tally_v1_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tally_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_tally_v1_transaction_proto_depIdxs,
		EnumInfos:         file_api_tally_v1_transaction_proto_enumTypes,
		MessageInfos:      file_api_tally_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_tally_v1_transaction_proto = out.File
	file_api_tally_v1_transaction_proto_goTypes = nil
	file_api_tally_v1_transaction_proto_depIdxs = nil
}
