// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/tally/v1/transaction.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TallyService_Record_FullMethodName = "/tally.v1.TallyService/Record"
	TallyService_List_FullMethodName   = "/tally.v1.TallyService/List"
	TallyService_Get_FullMethodName    = "/tally.v1.TallyService/Get"
	TallyService_Delete_FullMethodName = "/tally.v1.TallyService/Delete"
)

// TallyServiceClient is the client API for TallyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TallyServiceClient interface {
	// Record creates a new income or expense entry.
	// 记账：创建一条收入或支出记录。
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Transaction, error)
	// List queries transactions with optional filters and pagination.
	// 查账：查询交易记录列表，支持筛选和分页。
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Get retrieves details of a single transaction.
	// 查单条：获取某条记录的详情。
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Transaction, error)
	// Delete removes a transaction permanently.
	// 删账：永久删除一条记录（用于记错时修正）。
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tallyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTallyServiceClient(cc grpc.ClientConnInterface) TallyServiceClient {
	return &tallyServiceClient{cc}
}

func (c *tallyServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, TallyService_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tallyServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, TallyService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tallyServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, TallyService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tallyServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TallyService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TallyServiceServer is the server API for TallyService service.
// All implementations must embed UnimplementedTallyServiceServer
// for forward compatibility.
type TallyServiceServer interface {
	// Record creates a new income or expense entry.
	// 记账：创建一条收入或支出记录。
	Record(context.Context, *RecordRequest) (*Transaction, error)
	// List queries transactions with optional filters and pagination.
	// 查账：查询交易记录列表，支持筛选和分页。
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Get retrieves details of a single transaction.
	// 查单条：获取某条记录的详情。
	Get(context.Context, *GetRequest) (*Transaction, error)
	// Delete removes a transaction permanently.
	// 删账：永久删除一条记录（用于记错时修正）。
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTallyServiceServer()
}

// UnimplementedTallyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTallyServiceServer struct{}

func (UnimplementedTallyServiceServer) Record(context.Context, *RecordRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedTallyServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTallyServiceServer) Get(context.Context, *GetRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTallyServiceServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTallyServiceServer) mustEmbedUnimplementedTallyServiceServer() {}
func (UnimplementedTallyServiceServer) testEmbeddedByValue()                      {}

// UnsafeTallyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TallyServiceServer will
// result in compilation errors.
type UnsafeTallyServiceServer interface {
	mustEmbedUnimplementedTallyServiceServer()
}

func RegisterTallyServiceServer(s grpc.ServiceRegistrar, srv TallyServiceServer) {
	// If the following call pancis, it indicates UnimplementedTallyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TallyService_ServiceDesc, srv)
}

func _TallyService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TallyServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TallyService_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TallyServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TallyService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TallyServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TallyService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TallyServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TallyService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TallyServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TallyService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TallyServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TallyService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TallyServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TallyService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TallyServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TallyService_ServiceDesc is the grpc.ServiceDesc for TallyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TallyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tally.v1.TallyService",
	HandlerType: (*TallyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _TallyService_Record_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TallyService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TallyService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TallyService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tally/v1/transaction.proto",
}
